[template]
backend = "etcdv3"

log-level = "debug"
interval = 1
watch = true
noop = false

src = "default.conf.tmpl"
dest = "/etc/nginx/conf.d/default.conf"

keys = [
    "/nginx/domain"
]

# Tell confd where the backend nodes are
nodes = [
  "http://10.5.0.100:2379",
]

# Test and restart server
check_cmd = "nginx -t"
reload_cmd = "nginx -s reload"
