[template]
backend = "etcdv3"

log-level = "debug"
interval = 60
noop = false
watch = true

src = "default.conf.tmpl"
dest = "/etc/nginx/conf.d/default.conf"

keys = [
    "/nginx/domain"
]

nodes = [
  "http://10.5.0.100:2379",
]

check_cmd = "nginx -t"
reload_cmd = "nginx -s reload"
